export const SET_EVENTS_COLLECTIONS = '@query-creator/SET_EVENTS_COLLECTIONS';

export const FETCH_COLLECTION_SCHEMA = '@query-creator/FETCH_COLLECTION_SCHEMA';
export const FETCH_COLLECTION_SCHEMA_SUCCESS =
  '@query-creator/FETCH_COLLECTION_SCHEMA_SUCCESS';
export const FETCH_COLLECTION_SCHEMA_ERROR =
  '@query-creator/FETCH_COLLECTION_SCHEMA_ERROR';
export const SET_COLLETION_SCHEMA_LOADING =
  '@query-creator/SET_COLLETION_SCHEMA_LOADING';
export const SCHEMA_COMPUTED = '@query-creator/SCHEMA_COMPUTED';
