import { appSaga } from './appSaga';
import { appReducer, appSlice } from './reducer';
import {
  // showConfirmation,
  // hideConfirmation,
  // acceptConfirmation,
  // setVisualization,
  loadPersistedState,
  // setViewMode,
  updateQueryCreator,
  queryEditorMounted,
  notificationsMounted,
  explorerMounted,
  // showQuerySettingsModal,
  // hideQuerySettingsModal,
  showEmbedModal,
  hideEmbedModal,
  createNewQuery,
  switchToQueriesList,
  clearQuery,
  editQuery,
  shareQueryUrl,
  selectFirstSavedQuery,
  // appStart,
  exportChartToImage,
  exportChartToJson,
  exportDataToCsv,
  copyEmbeddedCode,
  downloadCodeSnippet,
  // showEmailExtractionModal,
  // hideEmailExtractionModal,
  copyApiResourceUrl,
  // setQueryAutorun,
  updateChartSettings,
  updateWidgetSettings,
  updateVisualizationType,
  // resetVisualization,
  // setQueriesFilters,
  // setQueriesSortSettings,
} from './actions';
import {
  getConfirmation,
  getViewMode,
  getQuerySettingsModalSource,
  getQuerySettingsModalVisibility,
  getEmbedModalVisibility,
  getExtractToEmailModalVisibility,
  getVisualization,
  getBrowserScreenDimension,
  getQueryAutorun,
  getQueriesFilters,
  getQueriesSortSettings,
} from './selectors';

import {
  HIDE_CONFIRMATION,
  ACCEPT_CONFIRMATION,
  HIDE_EMAIL_EXTRACTION_MODAL,
  QUERY_EDITOR_MOUNTED,
  DEFAULT_DIRECTION,
  DEFAULT_PROPERTY,
} from './constants';
// import { appSlice } from './reducer';

// const appReducer = appSlice.reducer;
const appActions = {
  // showConfirmation,
  // hideConfirmation,
  // acceptConfirmation,
  // setVisualization,
  loadPersistedState,
  // setViewMode,
  updateQueryCreator,
  queryEditorMounted,
  notificationsMounted,
  explorerMounted,
  // showQuerySettingsModal,
  // hideQuerySettingsModal,
  showEmbedModal,
  hideEmbedModal,
  createNewQuery,
  switchToQueriesList,
  clearQuery,
  editQuery,
  shareQueryUrl,
  selectFirstSavedQuery,
  // appStart,
  exportChartToImage,
  exportChartToJson,
  exportDataToCsv,
  copyEmbeddedCode,
  downloadCodeSnippet,
  // showEmailExtractionModal,
  // hideEmailExtractionModal,
  copyApiResourceUrl,
  // setQueryAutorun,
  updateChartSettings,
  updateWidgetSettings,
  updateVisualizationType,
  // resetVisualization,
  // setQueriesFilters,
  // setQueriesSortSettings,
  ...appSlice.actions,
};

export {
  // appStart,
  appReducer,
  appSlice,
  appSaga,
  appActions,
  // showConfirmation,
  // hideConfirmation,
  // acceptConfirmation,
  // shareQueryUrl,
  // clearQuery,
  // createNewQuery,
  // switchToQueriesList,
  // updateQueryCreator,
  // queryEditorMounted,
  // notificationsMounted,
  // explorerMounted,
  // editQuery,
  // setViewMode,
  getViewMode,
  // loadPersistedState,
  // setVisualization,
  getConfirmation,
  getBrowserScreenDimension,
  getQuerySettingsModalSource,
  getQuerySettingsModalVisibility,
  getEmbedModalVisibility,
  getVisualization,
  // showQuerySettingsModal,
  // hideQuerySettingsModal,
  // showEmbedModal,
  // hideEmbedModal,
  getExtractToEmailModalVisibility,
  // showEmailExtractionModal,
  // hideEmailExtractionModal,
  // selectFirstSavedQuery,
  // exportChartToImage,
  // exportChartToJson,
  // copyEmbeddedCode,
  // downloadCodeSnippet,
  // exportDataToCsv,
  // copyApiResourceUrl,
  // setQueryAutorun,
  getQueryAutorun,
  // updateChartSettings,
  // updateWidgetSettings,
  // updateVisualizationType,
  // resetVisualization,
  // setQueriesFilters,
  getQueriesFilters,
  // setQueriesSortSettings,
  getQueriesSortSettings,
};

export * from './types';

export {
  HIDE_CONFIRMATION,
  ACCEPT_CONFIRMATION,
  HIDE_EMAIL_EXTRACTION_MODAL,
  QUERY_EDITOR_MOUNTED,
  DEFAULT_DIRECTION,
  DEFAULT_PROPERTY,
};
