var keyMirror = require('keymirror');

module.exports = keyMirror({
  EXPLORER_CREATE: null,
  EXPLORER_CREATE_BATCH: null,
  EXPLORER_UPDATE: null,
  EXPLORER_REMOVE: null,
  EXPLORER_SET_ACTIVE: null,
  EXPLORER_CLEAR: null,
  EXPLOER_QUERY_SUCCESS: null,
  EXPLOER_QUERY_ERROR: null,
  EXPLORER_ADD_FILTER: null,
  EXPLORER_REMOVE_FILTER: null,
  EXPLORER_UPDATE_FILTER: null,
  EXPLORER_SAVE: null,
  EXPLORER_SAVE_NEW: null,
  EXPLORER_DESTROY: null,
  EXPLORER_SAVING: null,
  EXPLORER_SAVE_SUCCESS: null,
  EXPLORER_SAVE_FAIL: null,
  EXPLORER_DESTROYING: null,
  EXPLORER_DESTROY_SUCCESS: null,
  EXPLORER_DESTROY_FAIL: null
});
