export const UPDATE_SAVED_QUERY = 'UPDATE_SAVED_QUERY';
export const RESET_SAVED_QUERY = 'RESET_SAVED_QUERY';
export const SAVE_QUERY_SUCCESS = 'SAVE_QUERY_SUCCESS';
export const SELECT_SAVED_QUERY = 'SELECT_SAVED_QUERY';
